name: build_binary

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch: {}

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.25.1"

      - name: "Build binary"
        run: |
          deno compile --allow-read --allow-net --target x86_64-unknown-linux-gnu --output=./tonkaz_x86_64-unknown-linux-gnu src/main.ts
          deno compile --allow-read --allow-net --target x86_64-apple-darwin --output=./tonkaz_x86_64-apple-darwin src/main.ts
          deno compile --allow-read --allow-net --target aarch64-apple-darwin --output=./tonkaz_aarch64-apple-darwin src/main.ts

      - name: "Upload x86_64-unknown-linux-gnu binary"
        uses: actions/upload-artifact@v3
        with:
          name: tonkaz_x86_64-unknown-linux-gnu
          path: tonkaz_x86_64-unknown-linux-gnu

      - name: "Upload x86_64-apple-darwin binary"
        uses: actions/upload-artifact@v3
        with:
          name: tonkaz_x86_64-apple-darwin
          path: tonkaz_x86_64-apple-darwin

      - name: "Upload aarch64-apple-darwin binary"
        uses: actions/upload-artifact@v3
        with:
          name: tonkaz_aarch64-apple-darwin
          path: tonkaz_aarch64-apple-darwin
